### ISSUE TITLE
uci: I/O error

### ISSUE THREAD

**Issue by dream10201** [acc-/tplink-archer-c2300#1]
admin@AC2300:/root$ uci set openvpn.server.verbose=4
Result ：
uci: I/O error

**Comment by acc-** [comment]
Looks strange and dangerous, might be something wrong with your router's memory or so.

Did you try 'Backup' download method (decrypting to xml, updating manually, encrypting and uploading using 'Restore') ?

Which firmware do you have? I have just tested it on '2.0.3 Build 20180810 Rel. 62903' and it works for me.
```
root@AC2300:~#  uci show openvpn.server.verbose
openvpn.server.verbose=3
root@AC2300:~#  uci set openvpn.server.verbose=4
root@AC2300:~#  uci show openvpn.server.verbose
openvpn.server.verbose=4
```

**Comment by dream10201** [comment]
Software version：2.0.0 Build 20170922 Rel. 32364(5553/5553)
Backup and restore xml is available
Taiwanese machine

**Comment by acc-** [comment]
try ready to use scripts [described here](https://github.com/acc-/tplink-archer-c2300/wiki/Backup-Restore-config-files) to modify your openvpn server verbose parameter

**Comment by dream10201** [comment]
What parameters should be modified?

**Comment by dream10201** [comment]
I want to get full root privileges

**Comment by dream10201** [comment]
![image](https://user-images.githubusercontent.com/20334372/60073549-583d4180-9753-11e9-9660-35ff86fdc613.png)

**Comment by acc-** [comment]
ah, so you're not root, that's why you have uci I/O error... you need UART then connected and follow the instructions [here](https://github.com/acc-/tplink-archer-c2300/wiki/Full-SSH-access-with-real-root-account)

**Comment by dream10201** [comment]
Thank you
