### ISSUE TITLE
Can't convert binary file to xml

### ISSUE THREAD

**Issue by TossMySalad** [acc-/tplink-archer-c2300#10]
I have a similar problem as in here: https://github.com/acc-/tplink-archer-c2300/issues/5
However, I'm providing the correct backup binary file as the argument for the bin2xml.sh script.

I compiled openssl 1.1.1h with zlib support as instructed in the tutorial.

The output of the script:
`
File MD5: 702d64cdfb9983b9bde340af8e41a1e1, product MD5: b37598ac5105ea9974fc6634a4c92a76
MD5 product name mismatch, beware when using xml2bin !!!
bad decrypt
140503195449152:error:29065064:lib(41):bio_zlib_read:zlib inflate error:crypto/comp/c_zlib.c:400:zlib error:data error
140489760245568:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:583:
XML file saved in router-config.xml
`

Also I've tried to modify the script to use pigz instead of zlib, as instructed in the previous ticket. The output of the modified script:

`
File MD5: 702d64cdfb9983b9bde340af8e41a1e1, product MD5: b37598ac5105ea9974fc6634a4c92a76
MD5 product name mismatch, beware when using xml2bin !!!
bad decrypt
140179845343040:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:583:
pigz: skipping: <stdin> unrecognized format
XML file saved in router-config.xml
`

Hardware version: Archer C2300 v2.0 (from your examples in the wiki, I see that yours is v1.0, maybe this could be the problem?)
I have upgraded the firmware from 1.0.3 something to 1.1.0 Build 20200714 rel.30791(4555), but the errors are the same and I'm not sure if the backup file changed at all.
Maybe I need some different firmware?

I don't really understand how the script works and the error messages that I get.
Any help or clues what to do would be very appreciated.

**Comment by acc-** [comment]
It looks your router is totally different then - I suggest not to use my scripts at all.

**Comment by TossMySalad** [comment]
Oh, ok. 
How did you go about figuring out how to decrypting your config? How did you analyze the file?

**Comment by acc-** [comment]
I described it [here](https://github.com/acc-/tplink-archer-c2300/wiki/Backup-Restore-config-files#original-firmware-backup-script-details-for-experienced-users) and generally as I remember it was a very painful task to figure it out...
