### ISSUE TITLE
Router Brick - AC3200

### ISSUE THREAD

**Issue by rodneyoh** [acc-/tplink-archer-c2300#7]
Hello friend, how are you?
I searched a lot on the internet and found no one who knew the Archer C3200. Although you are talking about the C2300, I am sending this message because I saw that you have a lot of knowledge about TP-Link routers.
Could you please try to help me?
I performed a firmware update through the browser that didn't work, now the router turns on with 3 fixed lights and nothing else, I tried to access it via TFTP with a UART card, but nothing happens.
I removed the memory chip and did the direct recording of the firmware downloaded from the manufacturer using the CH341a recorder, without success.
Could you help me with this router revival process?
Thank you.

**Comment by acc-** [comment]
Sorry, this goes beyond my knowledge, I'm not able to help.

**Comment by rodneyoh** [comment]
ok my friend, anyway i thank you for the answer.
Hugs!
