### ISSUE TITLE
cross compiled file 

### ISSUE THREAD

**Issue by tryitagain** [acc-/tplink-archer-c2300#8]
Hi Acc,

Can you give more direction more detail  after I install tool chain  by  following your wiki ,please ? https://github.com/acc-/tplink-archer-c2300/wiki/Cross-compiling
let say to  build openvpn binary 
Thank you

**Comment by acc-** [comment]
Sorry, I do not remember anything else. I installed toolchain from the repo I referenced and that's all.. In the readme of https://github.com/acc-/tplink-archer-c2300/tree/master/cross-compiled-files I put what config options I used for busybox and dropbear. I don't remember openvpn - I guess it was the default one with just toolchain setup

**Comment by tryitagain** [comment]
Thank you  for your help  and  that's  clear up .

**Comment by tryitagain** [comment]
Hi Adam,
Just let you know that after tun0 connected just need only a config/network
only with
option ifname ‘tun0’
option proto ‘none’
Thank you
